# nonk8s
apiVersion: skagents/v2alpha1
kind: Agent
name: AssistantAgent
version: 0.1
metadata:
  description: >
    Generate a report based on a given topic
  skills:
    - name: generate_report
      description: >
        Generate a report based on a given topic
      examples:
        - Using the context provided, generate a comprehensive report on narwhals
spec:
  agent:
    name: AssistantAgent
    model: gpt-4o
    system_prompt: >
      You are a helpful assistant. Your task is to synthesize data extracted
      into a high quality literature review including CORRECT references. You
      MUST write a final report that is formatted as a literature review with
      CORRECT references.